
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://frffrnqzibkhhrknohlu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZyZmZybnF6aWJraGhya25vaGx1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4NzY2NDAsImV4cCI6MjA2MDQ1MjY0MH0.jS6ngycGoN3QBoxxDkSKGeqWTjl5_JsLsBuwWVXR1Bc";

// Initialize the supabase client with additional options
export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      autoRefreshToken: true,
      persistSession: true,
    }
  }
);
